/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Player.View;

import Interface.DAO;
import Player.Model.Entity.Player;
import Player.Model.Repository.JDBC.PlayerDAOJDBC;
import java.sql.SQLException;

/**
 *
 * @author retam
 */
public class PlayerView extends javax.swing.JPanel {

    private final DAO<Player> playerDAO;
    private Player player;

    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
        this.playerDAO = new PlayerDAOJDBC();
        this.player = new Player();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCreatePlayer = new javax.swing.JButton();
        tfName = new javax.swing.JTextField();
        bDeletePlayer = new javax.swing.JButton();

        bCreatePlayer.setText("Crear player");
        bCreatePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreatePlayerActionPerformed(evt);
            }
        });

        tfName.setText("jTextField1");

        bDeletePlayer.setText("Eliminar Player");
        bDeletePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeletePlayerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(bCreatePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(bDeletePlayer))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bCreatePlayer)
                .addGap(18, 18, 18)
                .addComponent(bDeletePlayer))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCreatePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreatePlayerActionPerformed

        this.player.setName(this.tfName.getText());
        this.playerDAO.crear(this.player);

    }//GEN-LAST:event_bCreatePlayerActionPerformed

    private void bDeletePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeletePlayerActionPerformed
        this.playerDAO.eliminar(this.player.getId());
    }//GEN-LAST:event_bDeletePlayerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCreatePlayer;
    private javax.swing.JButton bDeletePlayer;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
